<?php include $phireHeader; ?>
        <h1 id="form-title" data-title="<?php echo (isset($data_title) ? $data_title : null); ?>"><?php $i18n->_e('Extensions'); ?> <?php echo $separator; ?> <?php $i18n->_e('Modules'); ?> <?php echo $separator; ?> <?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if ($acl->isAuth('Forms\Controller\Forms\IndexController', 'add')): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/forms/add">+ <?php $i18n->_e('Add'); ?></a>
<?php endif; ?>
<?php if (isset($form)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/forms"><?php $i18n->_e('Back'); ?></a>
<?php echo $form;
elseif (isset($table)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/extensions/modules"><?php $i18n->_e('Back'); ?></a>
<?php echo $table;
else: ?>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There are currently no forms.'); ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>