<?php include $phireHeader; ?>
        <h1><?php $i18n->_e('Extensions'); ?> <?php echo $separator; ?> <?php $i18n->_e('Modules'); ?> <?php echo $separator; ?> <?php echo $title; ?></h1>
        <div id="result" style="display: none;"></div>
<?php if (isset($submission)): ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/forms/view/<?php echo $formId; ?>"><?php $i18n->_e('Back'); ?></a>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0" style="border-bottom: solid 1px #ccc; border-left: solid 1px #ccc; border-right: solid 1px #ccc;">
            <tr><th colspan="2"><?php echo $submitDate; ?><span style="font-weight: normal; float: right;"><?php echo $ipAddress; ?></span></th></tr>
<?php foreach ($submission as $name => $value): ?>
            <tr><td><strong><?php echo $name; ?></strong></td><td><?php
if (is_array($value)):
    echo implode(', ', $value);
else:
    echo (file_exists(__DIR__ . '/../../data/files/' . $value)) ? '<a href="' . BASE_PATH . CONTENT_PATH . '/extensions/modules/Forms/data/files/' . $value . '" target="_blank">' . $value . '</a>' : $value;
endif;
?></td></tr>
<?php endforeach; ?>
        </table>
<?php elseif (isset($table)): ?>
<?php if ($acl->isAuth('Forms\Controller\Forms\IndexController', 'export')): ?>
        <a class="export-btn" href="<?php echo BASE_PATH . APP_URI; ?>/forms/export/<?php echo $formId; ?>"><?php $i18n->_e('Export'); ?></a>
<?php endif; ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/forms"><?php $i18n->_e('Back'); ?></a>
<?php echo $table;
else: ?>
        <a class="small-btn" href="<?php echo BASE_PATH . APP_URI; ?>/forms"><?php $i18n->_e('Back'); ?></a>
        <p style="clear: left; padding: 15px 0 0 0;"><?php $i18n->_e('There are currently no form submissions.'); ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>